const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/home'))
  .get('/userHomepage', (req, res) => res.render('pages/userHomepage'))
  .get('/wishList', (req, res) => res.render('pages/wishList'))
  .get('/addToJournal', (req, res) => res.render('pages/addToJournal'))
  .get('/addToWishList', (req, res) => res.render('pages/addToWishList'))
  .get('/createProfile', (req, res) => res.render('pages/createProfile'))
  .get('/editTrip', (req, res) => res.render('pages/editTrip'))
  .get('/search', (req, res) => res.render('pages/search'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
